import shopBagDesktop from "../../assets/hero/largetall_2x.mp4";
import shopBagMobile from "../../assets/hero/small_2x.mp4";

import threeIphoneMobile from "../../assets/hero/hero_iphone_family__fuz5j2v5xx6y_small_2x.jpg";
import threeIphoneDesktop from "../../assets/hero/hero_iphone_family__fuz5j2v5xx6y_largetall_2x.jpg";
import airPodDesktop from "../../assets/hero/hero_ipad_air_avail__c34ycq52exg2_mediumtall_2x.jpg";
import airPodMoible from "../../assets/hero/hero_ipad_air_avail__c34ycq52exg2_small_2x.jpg";
const menuItems = [
  {
    name: "Store",
    items: [
      "Shop Gift",
      "Mac",
      "iPad",
      "iPhone",
      "Apple Watch",
      "Apple Vision Pro",
      "AirPods",
      "Accessories",
    ],
    firstTitle: "Shop",
    foot1: "Compare iPad",
    secondTitle: "Quick Links",
    secondItem: [
      "Find a Store",
      "Order Status",
      "Apple Trade In",
      "Financing",
      "Personal Setup",
    ],
    thirdTittle: "Shop Specail Stores",
    thirdItem: [
      "Certtifield Refurbished",
      "Education",
      "Business",
      "Veterans and Military",
      "Government",
    ],
  },
  {
    name: "Mac",
    items: [
      "MacAir",
      "Macbook Pro",
      "iMac",
      "Mac Mini",
      "Mac Studios",
      "Display",
    ],
    firstTitle: "Explore Mac",
    foot1: "Compare Mac",
    foot2: "Switch from PC to Mac",
    secondTitle: "Shop Mac",
    secondItem: [
      "Shop Mac",
      "Help Me Choose",
      "Mac Accesories",
      "Apple Trade In",
      "Finanacing",
      "Personal Setup",
    ],
    thirdTittle: "More from Mac",
    thirdItem: [
      "Mac Support",
      "AppleCare",
      "macOS Tahoe",
      "Apple Intelligence",
      "Apps by Apple",
      "Better with iPhone",
      "iCloud+",
      "Mac for business",
      "Education",
    ],
  },
  {
    name: "iPad",
    items: [
      "Explore All iPad",
      "iPad Pro",
      "iPad Air",
      "iPad",
      "iPad Mini",
      "Apple Pencil",
      "Keyboards",
    ],
    firstTitle: "Explore iPad",
    foot1: "Compare iPad",
    secondTitle: "Shop iPad",
    secondItem: [
      "Shop iPad",
      "iPad Accessories",
      "Apple Trade In",
      "Financing",
      "Personal Setup",
    ],
    thirdTittle: "More from iPad",
    thirdItem: [
      "iPad Support",
      "AppleCare",
      "iPadOS 26",
      "Apple Intelligence",
      "Apps by Apple",
      "iCloud+",
      "Education",
    ],
  },
  {
    name: "iPhone",
    items: [
      "Explore All iPhone ",
      "iPhone 17 Pro",
      "iPhone Air",
      "iPhone 17",
      "iPhone 16",
      "iPhone 16e",
    ],
    firstTitle: "Explore iPhone",
    foot1: "Compare iPhone",
    foot2: "Switch from Android",
    secondTitle: "Shop iPhone",
    secondItem: [
      "Shop iPhone",
      "iPhone Accessories",
      "Carrier Deals at Apple",
      "Financing",
      "Personal Setup",
    ],
    thirdTittle: "More from iPhone",
    thirdItem: [
      "iPhone Support",
      "AppleCare",
      "iOS 26",
      "Apple Intelligence",
      "Apple by Apple",
      "iPhone Privacy",
      "Better with Mac",
      "iCloud+",
      "Wallet, Pay, Card",
      "Siri",
    ],
  },
  {
    name: "Watch",
    items: [
      "Explore All Apple Watch",
      "Apple Watch SE3",
      "Apple Watch Ultra 3",
      "Apple Watch Nike",
      "Apple Watch Hermès",
    ],
    firstTitle: "Explore Watch",
    foot1: "Compare Watch",
    foot2: "Why Appple Watch",
    secondTitle: "Shop Watch",
    secondItem: [
      "Shop Apple Watch",
      "Shope Watch Bands",
      "Apple Watch Accessories",
      "Apple Trade In",
    ],
    thirdTittle: "More from Watch",
    thirdItem: [
      "Apple Watch Support",
      "AppleCare",
      "watchOS 26",
      "Apple Watch For Your Kids",
      "Apple by Apple",
      "Apple Fitness+",
    ],
  },
  {
    name: "Vision",
    items: ["Explore Apple Vision Pro"],
    firstTitle: "Explore Vision",
    foot1: "Tech Specs",
    secondTitle: "Shop Vision",
    secondItem: [
      "Shop Apple Vision Pro",
      "Apple Vision Pro Accessories",
      "Book a Demo",
      "Financing",
      "Personal Setup",
    ],
    thirdTittle: "More from Vision",
    thirdItem: ["Apple Vision Pro Support", "AppleCare", "versionOS 26"],
  },
  {
    name: "Airpods",
    items: [
      "Explore All AirPods",
      "AirPods 4t",
      "AirPods Pro 3",
      "AirPods Max",
    ],
    firstTitle: "Explore AirPods",
    foot1: "Compare AirPods",
    secondTitle: "Shop AirPods",
    secondItem: ["Shop AirPods", "AirPods Accessories"],
    thirdTittle: "More from Airpods",
    thirdItem: [
      "AirPods Support",
      "AppleCare",
      "Hearing Health",
      "Apple Music",
      "Apple Fitness+",
    ],
  },
  {
    name: "TV & Home",
    items: ["Explore TV & Home", "Apple TV 4K", "HomePod Mini"],
    firstTitle: "Explore Tv & Home",
    secondTitle: "Shop TV & Home",
    secondItem: [
      "Shop Apple TV 4K",
      "Shop HomePod mini",
      "Shop Siri Remote",
      "Tv & Home Accessories",
    ],
    thirdTittle: "More from TV & Home",
    thirdItem: [
      "Apple TV Support",
      "HomePod Support",
      "AppleCare for Apple TV",
      "AppleCare for HomePods",
      "Apple TV app",
      "Apple TV",
      "Home App",
      "Apple Music",
      "Siri",
      "AirPlay",
    ],
  },
  {
    name: "Entertainment",
    items: [
      "Explore Entertainment",
      "Apple One",
      "Apple TV",
      "Apple Music",
      "Apple Arcade",
      "Apple Fitness+",
      "Apple PodCasts",
      "Apple Books",
      "Apple Stores",
    ],
    firstTitle: "Explore Entertainment",
    secondTitle: "Support",
    secondItem: ["Apple TV Support", "Apple Music Support"],
  },
  {
    name: "Accessories",
    items: [
      "Shop All Accesories",
      "Mac",
      "iPad",
      "iPhone",
      "Apple Watch",
      "Apple Vision Pro",
      "AirPods",
      "Tv & Home",
    ],
    firstTitle: "Shop Accessories",
    secondTitle: "Explore Accessories",
    secondItem: ["Made by Apple", "Beats", "AirTag", "Assisitive Technologies"],
  },
  {
    name: "Support",
    items: [
      "iPhone",
      "Mac",
      "iPad",
      "Watch",
      "Apple Vision Pro",
      "Airpods",
      "Music",
      "TV",
    ],
    firstTitle: "Explore Support",
    foot1: "Explore Support",
    secondTitle: "Get Help",
    secondItem: ["Community", "Check Coverge", "Genuis Bar", "Repair"],
    thirdTittle: "Helpful Topic",
    thirdItem: [
      "Get AppleCare",
      "Apple Accounnt and Password",
      "Billing & Subscription",
      "Acessibilty",
    ],
  },
  {
    searchItem: [
      "Shop Gift",
      "Find a Stored",
      "Apple Gift Card",
      "Apple Vision Pro",
      "Apple Trade",
    ],
  },
];

const imageHome = [
  { videoDesktop: shopBagDesktop, videoMobile: shopBagMobile },
  { imageDesktop: threeIphoneDesktop, imageMobile: threeIphoneMobile },
  { imageDesktop: airPodDesktop, imageMobile: airPodMoible },
];

const heroItem = [
  {
    title: "Wraaping up this special season.",
    description: "There`s still time to make thier holiday one of kind. ",
  },
  {
    title: "iPhone",
    description: "Say hello to the lastest generation of iPhone. ",
  },
  { title: "iPad Air", description: "Now Supercharged by M3 chip." },
];
const btnCss = [
  {
    title: "Learn More",
    css: "bg-[#0071e3] w-[104px] h-[36px] text-white lg:w-33 lg:h-11 hover:bg-[#0071e3] hover:text-white",
  },
  {
    title: "Buy ",
    css: "bg-transparent border border-[#0071e3] text-[#0071e3] w-[62px] h-[36px] Lg:w-[73.2px] lg:h-11 hover:bg-[#0071e3] hover:text-white",
  },
  {
    title: "Shop iPhone ",
    css: "bg-transparent border w-[114px] h-[36px] border-[#0071e3] text-[#0071e3]  lg:w-[140px] lg:h-11 hover:bg-[#0071e3] hover:text-white",
  },
  { title: "Shop gifts ", css: "bg-[#0071e3] w-[96px] h-9 text-white lg:w-[121px] lg:h-11" },
];
import logoIpadAirDesktop from "../../assets//logo/promo_logo_ipadair__frwnnsqveeye_medium_2x.png";
import logoIpadAirMobile from "../../assets//logo/hero_eyebrow_logo__ee6zpqgwfxm6_small_2x.png";
const logo = [{ title: "ipad air", logoDesktop: logoIpadAirDesktop,logoMobile:logoIpadAirMobile }];
export { btnCss };
export default menuItems;
export { imageHome };
export { heroItem };
export { logo };
